services:
  mariadb:
    image: mariadb:10.8
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=codeasy
      - MYSQL_USER=codeasy
      - MYSQL_PASSWORD=secretpass
    ports:
      - "4001:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # --- NGINX untuk serve Laravel di port 80 ---
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  # --- LARAVEL (PHP-FPM) ---
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  # --- FASTAPI ---
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
