services:
  mariadb:
    image: mariadb:10.8
    container_name: codeasy_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "4001:3306"            # Host port 4001 -> Container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: codeasy_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_queue
    command: php artisan queue:listen --tries=2 --queue=high,default
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  scheduler:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_scheduler
    command: php artisan schedule:work
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  laravel:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_dev
    command: composer dev
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    # Kita expose port 9001 dan 9002 agar "artisan serve" (9001) & "vite dev" (9002) bisa diakses
    ports:
      - "9001:9001"
      - "9002:9002"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "artisan", "--version"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    container_name: codeasy_fastapi
    volumes:
      - ./fastapi:/app
      # Tambahkan mount folder laravel agar FastAPI punya akses ke /var/www/html
      - ./laravel:/var/www/html
    ports:
      - "8001:8001"            # Gunakan 8001 di host
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: codeasy_nginx_laravel
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"              # Akses http://localhost:8080 untuk Nginx
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      fastapi:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: codeasy_phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      mariadb:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:latest
    container_name: codeasy_mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
