services:
  # --- NGINX untuk serve Laravel di port 80 ---
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app-network

  # --- LARAVEL (PHP-FPM) ---
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  # --- FASTAPI ---
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
