services:
  mariadb:
    image: mariadb:10.8
    container_name: codeasy_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "4001:3306"            # Host port 4001 -> Container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: codeasy_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_queue
    command: php artisan queue:listen --tries=2 --queue=high,default
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  scheduler:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_scheduler
    command: php artisan schedule:work
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  laravel:
    build:
      context: .
      dockerfile: docker/laravel.dev.Dockerfile
    container_name: codeasy_laravel_dev
    command: composer dev
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    # Kita expose port 9001 dan 9002 agar "artisan serve" (9001) & "vite dev" (9002) bisa diakses
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      - APP_URL=http://localhost:9001
      - VITE_DEV_SERVER_URL=http://localhost:9002
      - DOCKER_ENV=true
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "php artisan --version && curl -f http://localhost:9001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    container_name: codeasy_fastapi
    volumes:
      - ./fastapi:/app
      # Tambahkan mount folder laravel agar FastAPI punya akses ke /var/www/html
      - ./laravel:/var/www/html
    ports:
      - "8001:8001"            # Gunakan 8001 di host
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: codeasy_nginx_laravel
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"              # Akses http://localhost:8080 untuk Nginx
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      fastapi:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: codeasy_phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:80"
    volumes:
      - ./docker/phpmyadmin-uploads.ini:/usr/local/etc/php/conf.d/phpmyadmin-uploads.ini:ro
    networks:
      - app-network
    depends_on:
      mariadb:
        condition: service_healthy

  cypress-e2e:
    build:
      context: .
      dockerfile: docker/cypress.Dockerfile
    container_name: codeasy_cypress_e2e
    volumes:
      - ./laravel/cypress:/e2e/cypress
      - ./laravel/node_modules:/e2e/cypress/node_modules
    ports:
      - "5900:5900"   # VNC access
      - "6080:6080"   # noVNC web access
    environment:
      - CYPRESS_baseUrl=http://laravel:9001
      - DISPLAY=:99
      - TZ=Asia/Jakarta
    networks:
      - app-network
    depends_on:
      laravel:
        condition: service_healthy
      fastapi:
        condition: service_started
    # By default, start in interactive mode
    # Change to ["run"] for headless mode
    # Change to ["run-firefox"] for Firefox headless mode
    command: ["open"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
