<?php

namespace App\Support\Enums;

enum IntentEnum: string {
    case CUSTOM_ACTION = 'custom-action';

    case USER_INDEX_STUDENTS = 'user.index.students';
    case TEACHER_UPDATE_APPROVE = 'teacher.update.approve';
    case SCHOOL_UPDATE_ASSIGN_ADMIN = 'school.update.assign.admin';
    case SCHOOL_UPDATE_UNASSIGN_ADMIN = 'school.update.unassign.admin';
    case SCHOOL_UPDATE_ASSIGN_TEACHER = 'school.update.assign.teacher';
    case SCHOOL_UPDATE_UNASSIGN_TEACHER = 'school.update.unassign.teacher';
    case SCHOOL_REQUEST_UPDATE_APPROVE_TEACHER = 'school.request.update.approve.teacher';
    case SCHOOL_REQUEST_UPDATE_REJECT_TEACHER = 'school.request.update.reject.teacher';
    case SCHOOL_REQUEST_UPDATE_APPROVE_STUDENT = 'school.request.update.approve.student';
    case SCHOOL_REQUEST_UPDATE_REJECT_STUDENT = 'school.request.update.reject.student';
    case CLASS_ROOM_UPDATE_ASSIGN_STUDENT = 'classroom.update.assign.student';
    case CLASS_ROOM_UPDATE_UNASSIGN_STUDENT = 'classroom.update.unassign.student';
    case SCHOOL_UPDATE_ASSIGN_STUDENT = 'school.update.assign.student';
    case SCHOOL_UPDATE_UNASSIGN_STUDENT = 'school.update.unassign.student';
    case USER_INDEX_CLASS_ROOM_STUDENTS = 'user.index.classroom.students';
    case COURSE_STORE_IMPORT = 'course.store.import';
    case COURSE_INDEX_IMPORT_TEMPLATE = 'course.index.import.template';
    case COURSE_STORE_PREVIEW_IMPORT = 'course.store.preview.import';
    case DASHBOARD_INDEX_GET_DATA = 'dashboard.index.get.data';
    case DASHBOARD_INDEX_GET_STUDENT_COURSE_PROGRESS = 'dashboard.index.get.student.course.progress';
    case DASHBOARD_INDEX_GET_STUDENT_MATERIAL_PROGRESS = 'dashboard.index.get.student.material.progress';
    case DASHBOARD_INDEX_GET_STUDENT_PROGRESS = 'dashboard.index.get.student.progress';
    case DASHBOARD_INDEX_GET_STUDENT_LATEST_WORK = 'dashboard.index.get.student.latest.work';

    // Student Cognitive Classification intents
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT';
    case STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA';
    case STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION';

    // Student Course Cognitive Classification intents
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS';

    // Workspace locking intents
    case STUDENT_SCORE_STORE_REATTEMPT = 'STUDENT_SCORE_STORE_REATTEMPT';
    case STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE = 'STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE';
    case STUDENT_SCORE_INDEX_LOCKED_STUDENTS = 'STUDENT_SCORE_INDEX_LOCKED_STUDENTS';

    // PDF Base64 conversion intents
    case LEARNING_MATERIAL_INDEX_PDF_BASE64 = 'LEARNING_MATERIAL_INDEX_PDF_BASE64';

    // Answer completion intents
    case STUDENT_SCORE_UPDATE_MARK_AS_DONE = 'STUDENT_SCORE_UPDATE_MARK_AS_DONE';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL';

    case TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW = 'TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW';
}
