<?php

namespace App\Support\Enums;

enum IntentEnum: string {
    case CUSTOM_ACTION = 'custom-action';

    case USER_INDEX_STUDENTS = 'USER_INDEX_STUDENTS';
    case USER_STORE_IMPORT_STUDENTS = 'USER_STORE_IMPORT_STUDENTS';
    case USER_INDEX_IMPORT_STUDENTS_TEMPLATE = 'USER_INDEX_IMPORT_STUDENTS_TEMPLATE';
    case USER_INDEX_IMPORT_STUDENTS_CSV_TEMPLATE = 'USER_INDEX_IMPORT_STUDENTS_CSV_TEMPLATE';
    case USER_STORE_PREVIEW_IMPORT_STUDENTS = 'USER_STORE_PREVIEW_IMPORT_STUDENTS';
    case USER_UPDATE_PREFERENCES = 'USER_UPDATE_PREFERENCES';
    case TEACHER_UPDATE_APPROVE = 'TEACHER_UPDATE_APPROVE';
    case SCHOOL_UPDATE_ASSIGN_ADMIN = 'SCHOOL_UPDATE_ASSIGN_ADMIN';
    case SCHOOL_UPDATE_ASSIGN_BULK_ADMINS = 'SCHOOL_UPDATE_ASSIGN_BULK_ADMINS';
    case SCHOOL_UPDATE_UNASSIGN_ADMIN = 'SCHOOL_UPDATE_UNASSIGN_ADMIN';
    case SCHOOL_UPDATE_ASSIGN_TEACHER = 'SCHOOL_UPDATE_ASSIGN_TEACHER';
    case SCHOOL_UPDATE_UNASSIGN_TEACHER = 'SCHOOL_UPDATE_UNASSIGN_TEACHER';
    case SCHOOL_REQUEST_UPDATE_APPROVE_TEACHER = 'SCHOOL_REQUEST_UPDATE_APPROVE_TEACHER';
    case SCHOOL_REQUEST_UPDATE_REJECT_TEACHER = 'SCHOOL_REQUEST_UPDATE_REJECT_TEACHER';
    case SCHOOL_REQUEST_UPDATE_APPROVE_STUDENT = 'SCHOOL_REQUEST_UPDATE_APPROVE_STUDENT';
    case SCHOOL_REQUEST_UPDATE_REJECT_STUDENT = 'SCHOOL_REQUEST_UPDATE_REJECT_STUDENT';
    case CLASS_ROOM_UPDATE_ASSIGN_STUDENT = 'CLASS_ROOM_UPDATE_ASSIGN_STUDENT';
    case CLASS_ROOM_UPDATE_UNASSIGN_STUDENT = 'CLASS_ROOM_UPDATE_UNASSIGN_STUDENT';
    case CLASS_ROOM_UPDATE_BULK_ASSIGN_STUDENTS = 'CLASS_ROOM_UPDATE_BULK_ASSIGN_STUDENTS';
    case CLASS_ROOM_UPDATE_BULK_UNASSIGN_STUDENTS = 'CLASS_ROOM_UPDATE_BULK_UNASSIGN_STUDENTS';
    case SCHOOL_UPDATE_ASSIGN_STUDENT = 'SCHOOL_UPDATE_ASSIGN_STUDENT';
    case SCHOOL_UPDATE_UNASSIGN_STUDENT = 'SCHOOL_UPDATE_UNASSIGN_STUDENT';
    case SCHOOL_UPDATE_BULK_ASSIGN_STUDENTS = 'SCHOOL_UPDATE_BULK_ASSIGN_STUDENTS';
    case SCHOOL_UPDATE_BULK_UNASSIGN_STUDENTS = 'SCHOOL_UPDATE_BULK_UNASSIGN_STUDENTS';
    case USER_INDEX_CLASS_ROOM_STUDENTS = 'USER_INDEX_CLASS_ROOM_STUDENTS';
    case USER_INDEX_STUDENTS_BY_COURSE = 'USER_INDEX_STUDENTS_BY_COURSE';
    case COURSE_STORE_IMPORT = 'COURSE_STORE_IMPORT';
    case COURSE_INDEX_IMPORT_TEMPLATE = 'COURSE_INDEX_IMPORT_TEMPLATE';
    case COURSE_INDEX_IMPORT_MATERIAL_TEMPLATE = 'COURSE_INDEX_IMPORT_MATERIAL_TEMPLATE';
    case COURSE_STORE_PREVIEW_IMPORT = 'COURSE_STORE_PREVIEW_IMPORT';
    case DASHBOARD_INDEX_GET_DATA = 'DASHBOARD_INDEX_GET_DATA';
    case DASHBOARD_INDEX_GET_STUDENT_COURSE_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_COURSE_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_MATERIAL_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_MATERIAL_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_LATEST_WORK = 'DASHBOARD_INDEX_GET_STUDENT_LATEST_WORK';
    case DASHBOARD_INDEX_GET_TEACHER_LATEST_PROGRESS = 'DASHBOARD_INDEX_GET_TEACHER_LATEST_PROGRESS';
    case DASHBOARD_INDEX_GET_TEACHER_COURSES = 'DASHBOARD_INDEX_GET_TEACHER_COURSES';
    case DASHBOARD_INDEX_GET_COURSE_LATEST_PROGRESS = 'DASHBOARD_INDEX_GET_COURSE_LATEST_PROGRESS';
    case DASHBOARD_INDEX_GET_COURSE_STUDENTS_NO_PROGRESS = 'DASHBOARD_INDEX_GET_COURSE_STUDENTS_NO_PROGRESS';
    case DASHBOARD_INDEX_GET_ACTIVE_USERS = 'DASHBOARD_INDEX_GET_ACTIVE_USERS';

    // Student Chart Data intents
    case DASHBOARD_INDEX_GET_STUDENT_LEARNING_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_LEARNING_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_COGNITIVE_LEVELS = 'DASHBOARD_INDEX_GET_STUDENT_COGNITIVE_LEVELS';
    case DASHBOARD_INDEX_GET_STUDENT_MODULE_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_MODULE_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_DAILY_ACTIVITY = 'DASHBOARD_INDEX_GET_STUDENT_DAILY_ACTIVITY';
    case DASHBOARD_INDEX_GET_STUDENT_WEEKLY_STREAK = 'DASHBOARD_INDEX_GET_STUDENT_WEEKLY_STREAK';
    case DASHBOARD_INDEX_GET_STUDENT_SCORE_TRENDS = 'DASHBOARD_INDEX_GET_STUDENT_SCORE_TRENDS';
    case DASHBOARD_INDEX_GET_STUDENT_TIME_ANALYSIS = 'DASHBOARD_INDEX_GET_STUDENT_TIME_ANALYSIS';
    case DASHBOARD_INDEX_GET_STUDENT_DIFFICULTY_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_DIFFICULTY_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_COMPARISON_STATS = 'DASHBOARD_INDEX_GET_STUDENT_COMPARISON_STATS';
    case DASHBOARD_INDEX_GET_STUDENT_ACHIEVEMENT_SUMMARY = 'DASHBOARD_INDEX_GET_STUDENT_ACHIEVEMENT_SUMMARY';

    // Student Cognitive Classification intents
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT';
    case STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA';
    case STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION';

    // Student Course Cognitive Classification intents
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS';

    // Workspace locking intents
    case STUDENT_SCORE_STORE_REATTEMPT = 'STUDENT_SCORE_STORE_REATTEMPT';
    case STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE = 'STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE';
    case STUDENT_SCORE_INDEX_LOCKED_STUDENTS = 'STUDENT_SCORE_INDEX_LOCKED_STUDENTS';

    // PDF Base64 conversion intents
    case LEARNING_MATERIAL_INDEX_PDF_BASE64 = 'LEARNING_MATERIAL_INDEX_PDF_BASE64';

    // Answer completion intents
    case STUDENT_SCORE_UPDATE_MARK_AS_DONE = 'STUDENT_SCORE_UPDATE_MARK_AS_DONE';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL';

    case STUDENT_SCORE_INDEX_EXPORT_TABULAR_DATA = 'STUDENT_SCORE_INDEX_EXPORT_TABULAR_DATA';
    case STUDENT_SCORE_INDEX_EXPORT_ENHANCED_DATA = 'STUDENT_SCORE_INDEX_EXPORT_ENHANCED_DATA';
    case STUDENT_SCORE_INDEX_GET_CLASSIFICATION_HISTORY_DATES = 'STUDENT_SCORE_INDEX_GET_CLASSIFICATION_HISTORY_DATES';

    case TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW = 'TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW';

    // Test Case Import intents
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_STORE_IMPORT = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_STORE_IMPORT';
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_INDEX_IMPORT_TEMPLATE = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_INDEX_IMPORT_TEMPLATE';
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_INDEX_IMPORT_CSV_TEMPLATE = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_INDEX_IMPORT_CSV_TEMPLATE';
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_STORE_PREVIEW_IMPORT = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_STORE_PREVIEW_IMPORT';
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_ALL_TEST_CASES_EXPORT_FILTERED = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_ALL_TEST_CASES_EXPORT_FILTERED';
    case LEARNING_MATERIAL_QUESTION_TEST_CASE_ALL_TEST_CASES_EXPORT_SEQUENCE_VALIDATION = 'LEARNING_MATERIAL_QUESTION_TEST_CASE_ALL_TEST_CASES_EXPORT_SEQUENCE_VALIDATION';
    case COURSE_INDEX_ENROLLED_STUDENT = 'COURSE_INDEX_ENROLLED_STUDENT';
}
