<?php

namespace App\Support\Enums;

enum IntentEnum: string {
    case CUSTOM_ACTION = 'custom-action';

    case USER_INDEX_STUDENTS = 'USER_INDEX_STUDENTS';
    case USER_STORE_IMPORT_STUDENTS = 'USER_STORE_IMPORT_STUDENTS';
    case USER_INDEX_IMPORT_STUDENTS_TEMPLATE = 'USER_INDEX_IMPORT_STUDENTS_TEMPLATE';
    case USER_INDEX_IMPORT_STUDENTS_CSV_TEMPLATE = 'USER_INDEX_IMPORT_STUDENTS_CSV_TEMPLATE';
    case USER_STORE_PREVIEW_IMPORT_STUDENTS = 'USER_STORE_PREVIEW_IMPORT_STUDENTS';
    case USER_UPDATE_PREFERENCES = 'USER_UPDATE_PREFERENCES';
    case TEACHER_UPDATE_APPROVE = 'TEACHER_UPDATE_APPROVE';
    case SCHOOL_UPDATE_ASSIGN_ADMIN = 'SCHOOL_UPDATE_ASSIGN_ADMIN';
    case SCHOOL_UPDATE_UNASSIGN_ADMIN = 'SCHOOL_UPDATE_UNASSIGN_ADMIN';
    case SCHOOL_UPDATE_ASSIGN_TEACHER = 'SCHOOL_UPDATE_ASSIGN_TEACHER';
    case SCHOOL_UPDATE_UNASSIGN_TEACHER = 'SCHOOL_UPDATE_UNASSIGN_TEACHER';
    case SCHOOL_REQUEST_UPDATE_APPROVE_TEACHER = 'SCHOOL_REQUEST_UPDATE_APPROVE_TEACHER';
    case SCHOOL_REQUEST_UPDATE_REJECT_TEACHER = 'SCHOOL_REQUEST_UPDATE_REJECT_TEACHER';
    case SCHOOL_REQUEST_UPDATE_APPROVE_STUDENT = 'SCHOOL_REQUEST_UPDATE_APPROVE_STUDENT';
    case SCHOOL_REQUEST_UPDATE_REJECT_STUDENT = 'SCHOOL_REQUEST_UPDATE_REJECT_STUDENT';
    case CLASS_ROOM_UPDATE_ASSIGN_STUDENT = 'CLASS_ROOM_UPDATE_ASSIGN_STUDENT';
    case CLASS_ROOM_UPDATE_UNASSIGN_STUDENT = 'CLASS_ROOM_UPDATE_UNASSIGN_STUDENT';
    case SCHOOL_UPDATE_ASSIGN_STUDENT = 'SCHOOL_UPDATE_ASSIGN_STUDENT';
    case SCHOOL_UPDATE_UNASSIGN_STUDENT = 'SCHOOL_UPDATE_UNASSIGN_STUDENT';
    case USER_INDEX_CLASS_ROOM_STUDENTS = 'USER_INDEX_CLASS_ROOM_STUDENTS';
    case COURSE_STORE_IMPORT = 'COURSE_STORE_IMPORT';
    case COURSE_INDEX_IMPORT_TEMPLATE = 'COURSE_INDEX_IMPORT_TEMPLATE';
    case COURSE_STORE_PREVIEW_IMPORT = 'COURSE_STORE_PREVIEW_IMPORT';
    case DASHBOARD_INDEX_GET_DATA = 'DASHBOARD_INDEX_GET_DATA';
    case DASHBOARD_INDEX_GET_STUDENT_COURSE_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_COURSE_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_MATERIAL_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_MATERIAL_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_PROGRESS = 'DASHBOARD_INDEX_GET_STUDENT_PROGRESS';
    case DASHBOARD_INDEX_GET_STUDENT_LATEST_WORK = 'DASHBOARD_INDEX_GET_STUDENT_LATEST_WORK';

    // Student Cognitive Classification intents
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT';
    case STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_STORE_RUN_CLASSIFICATION';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_RAW_DATA';
    case STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_MATERIAL_CLASSIFICATIONS';
    case STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION = 'STUDENT_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_CLASSIFICATION';

    // Student Course Cognitive Classification intents
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_BY_USER_AND_COURSE';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_GET_COURSE_REPORT';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_SHOW_DETAILS';
    case STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS = 'STUDENT_COURSE_COGNITIVE_CLASSIFICATION_INDEX_EXPORT_CALCULATION_STEPS';

    // Workspace locking intents
    case STUDENT_SCORE_STORE_REATTEMPT = 'STUDENT_SCORE_STORE_REATTEMPT';
    case STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE = 'STUDENT_SCORE_UPDATE_UNLOCK_WORKSPACE';
    case STUDENT_SCORE_INDEX_LOCKED_STUDENTS = 'STUDENT_SCORE_INDEX_LOCKED_STUDENTS';

    // PDF Base64 conversion intents
    case LEARNING_MATERIAL_INDEX_PDF_BASE64 = 'LEARNING_MATERIAL_INDEX_PDF_BASE64';

    // Answer completion intents
    case STUDENT_SCORE_UPDATE_MARK_AS_DONE = 'STUDENT_SCORE_UPDATE_MARK_AS_DONE';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT';
    case STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL = 'STUDENT_SCORE_UPDATE_ALLOW_REATTEMPT_ALL';

    case TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW = 'TEST_CASE_CHANGE_TRACKER_SHOW_EXECUTE_NOW';
}
