export enum FileTypeEnum {
    JPG = 'jpg',
    JPEG = 'jpeg',
    PNG = 'png',
    PDF = 'pdf',
    DOC = 'doc',
    DOCX = 'docx',
    PPT = 'ppt',
    PPTX = 'pptx',
    XLS = 'xls',
    XLSX = 'xlsx',
    TXT = 'txt',
    ZIP = 'zip',
    RAR = 'rar',
    MP4 = 'mp4',
    MP3 = 'mp3',
    WAV = 'wav',
    AVI = 'avi',
    FLV = 'flv',
    MOV = 'mov',
    MKV = 'mkv',
    WEBM = 'webm',
    OGG = 'ogg',
    OGV = 'ogv',
    WMV = 'wmv',
}
