const permissions = {
    USER_CREATE: 'user-create',
    USER_READ: 'user-read',
    USER_UPDATE: 'user-update',
    USER_DELETE: 'user-delete',
    PERMISSION_CREATE: 'permission-create',
    PERMISSION_READ: 'permission-read',
    PERMISSION_UPDATE: 'permission-update',
    PERMISSION_DELETE: 'permission-delete',
    ROLE_CREATE: 'role-create',
    ROLE_READ: 'role-read',
    ROLE_UPDATE: 'role-update',
    ROLE_DELETE: 'role-delete',
    SCHOOL_CREATE: 'school-create',
    SCHOOL_READ: 'school-read',
    SCHOOL_UPDATE: 'school-update',
    SCHOOL_DELETE: 'school-delete',
    STUDENT_CREATE: 'student-create',
    STUDENT_READ: 'student-read',
    STUDENT_UPDATE: 'student-update',
    STUDENT_DELETE: 'student-delete',
    TEACHER_CREATE: 'teacher-create',
    TEACHER_READ: 'teacher-read',
    TEACHER_UPDATE: 'teacher-update',
    TEACHER_DELETE: 'teacher-delete',
    CLASS_CREATE: 'class-create',
    CLASS_READ: 'class-read',
    CLASS_UPDATE: 'class-update',
    CLASS_DELETE: 'class-delete',
    SUBJECT_CREATE: 'subject-create',
    SUBJECT_READ: 'subject-read',
    SUBJECT_UPDATE: 'subject-update',
    SUBJECT_DELETE: 'subject-delete',
    EXAM_CREATE: 'exam-create',
    EXAM_READ: 'exam-read',
    EXAM_UPDATE: 'exam-update',
    EXAM_DELETE: 'exam-delete',
    RESULT_CREATE: 'result-create',
    RESULT_READ: 'result-read',
    RESULT_UPDATE: 'result-update',
    RESULT_DELETE: 'result-delete',
};

export const PermissionEnum = permissions;

export type PermissionEnum = (typeof permissions)[keyof typeof permissions];
