name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './laravel/package-lock.json'

      - name: Install dependencies
        working-directory: ./laravel
        run: npm ci

      - name: Run ESLint
        working-directory: ./laravel
        run: npm run lint

  prettier:
    name: Code Formatting Check
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './laravel/package-lock.json'

      - name: Install dependencies
        working-directory: ./laravel
        run: npm ci

      - name: Run Prettier
        working-directory: ./laravel
        run: npm run prettier

  build-and-push:
    name: Build & Push Docker Image
    needs: [lint, prettier]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_REPOSITORY_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/codeasy:latest \
            -f docker/laravel.prod.Dockerfile .

          docker push ghcr.io/${{ github.repository_owner }}/codeasy:latest

  deploy:
    name: Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          CR_PAT: ${{ secrets.IMAGE_REPOSITORY_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          DOCKER_CONFIG_CONTENT="{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n \"$GITHUB_ACTOR:$CR_PAT\" | base64)\"}}}"

          ssh $SSH_USERNAME@$SSH_HOST 'bash -s' << 'ENDSSH'
            set -ex

            mkdir -p ~/.docker
            echo "$DOCKER_CONFIG_CONTENT" > ~/.docker/config.json

            if [ ! -d "codeasy/.git" ]; then
              echo "Repo not found, cloning..."
              git clone https://github.com/evanightly/codeasy.git "codeasy"
            else
              echo "Repo already present, skipping clone."
            fi

            cd "codeasy"
            git fetch --all
            git reset --hard origin/main

            echo "${{ secrets.PRODUCTION_ENV }}" > laravel/.env || {
              echo "Failed to create .env file"
              exit 1
            }

            docker compose -f docker-compose.prod.yml down || echo "No containers to stop"
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            echo "Deployment completed!"
          ENDSSH